### ISSUE TITLE
add sharkteam 

### ISSUE THREAD

**Issue by 0x0918** [0xNazgul/Blockchain-Security-Audit-List#18]
Name: [SharkTeam](https://www.sharkteam.org/)                                                 
Reports: [Link](https://www.sharkteam.org/#auditReports)
Description: The World’s Leading Web3 Security Service Provider.

**Comment by 0xNazgul** [comment]
Added [a43619](https://github.com/0xNazgul/Blockchain-Security-Audit-List/commit/a43619f72a59ae24a4f1f70668f09216e426b882)
