### ISSUE TITLE
Reference : Methodology for determining "notable"

### ISSUE THREAD

**Issue by tormentr** [0xNazgul/Blockchain-Security-Audit-List#19]
Great list, but what criteria have you used to determine they are "notable" ? I am unable to find a quantitative resource and the README.MD has no indications about it ?

**Comment by 0xNazgul** [comment]
Good point on the word usage. When I started the list it was only "notable" or of high quality auditing companies. Since then the list has grown to more than that. I've removed the wording and will probably think more about some criteria to organize the list by quality of reports in the future.
