### ISSUE TITLE
How to handle solo auditor reports?

### ISSUE THREAD

**Issue by engn33r** [0xNazgul/Blockchain-Security-Audit-List#24]
Could a separate table listing solo auditors and their reports be created below the main table of audit companies?

I would expect someone will make a list of solo auditor reports at some point, so it might be easier to include that list here instead of a new repository. What approach do you prefer?

**Comment by 0xNazgul** [comment]
Something I have been meaning to get around to, thank you for the extra push. I've [added a few](https://github.com/0xNazgul/Blockchain-Security-Audit-List#solo-auditors) I know of and tried to find some more that are *"Available For Hire"* on Code4rena. 

I know there is more out there so feel free to be the first to add any that I initially missed!
