### ISSUE TITLE
Omniscia Company Correction

### ISSUE THREAD

**Issue by alex-ppg** [0xNazgul/Blockchain-Security-Audit-List#3]
Omniscia is a security company that actually performs audits, they do not reference any other firm's audits.

**Comment by 0xNazgul** [comment]
Nice catch! Haven't dived into their audit reports yet so didn't realize. So, I based it off first glance. 

Fixed: [commit#2ae56](https://github.com/0xNazgul/Blockchain-Security-Audit-List/commit/2ae56f20ddd598b36944f1421556688f51971ace)
