### ISSUE TITLE
Change the gogo name to George Hunter, he wants the world to forget about gogo

### ISSUE THREAD

**Issue by 0xnirlin** [0xNazgul/Blockchain-Security-Audit-List#42]
Recently GoGo changed his profile name to George Hunter so I urge you to change his name in this repo too.

Reference about his wish

https://x.com/GeorgeHNTR/status/1753470737120182729?s=20

**Comment by 0xNazgul** [comment]
Thank you for bringing this up! Fixed it with commit [`b5b441d`](https://github.com/0xNazgul/Blockchain-Security-Audit-List/commit/b5b441d98486aaf5b0ca98f04a222497c4d76f6e) and will be closing this issue.
